### ISSUE TITLE
[DOCS 📄] <description>

### ISSUE THREAD

**Issue by freecoursera** [freecoursera/freecoursera.github.io#34]
### Description

arrange the files in proper manner, attach ss for review
![image](https://github.com/freecoursera/freecoursera.github.io/assets/145432625/ca2fea7f-45a8-4fa2-ba9d-3ff0e2d5cd3f)

### Wanna Work upon[y/n] ??

no

**Comment by payallenka** [comment]
Kindly assign this issue to me.

**Comment by payallenka** [comment]
Also kindly add the Hacktoberfest tag to it.

**Comment by CodeTorso** [comment]
Someone did it. 

Closing PR.

**Comment by CodeTorso** [comment]
*issue
