### ISSUE TITLE
FEATURE REQUEST

### ISSUE THREAD

**Issue by freecoursera** [freecoursera/freecoursera.github.io#35]
### Description

fix the nav bar, it shouldn't scroll down with screen
![image](https://github.com/freecoursera/freecoursera.github.io/assets/145432625/2e9739b9-83ed-4ed3-9507-79e0f65e0236)

### Wanna Work upon[y/n] ??

no

**Comment by DhairyaMajmudar** [comment]
@freecoursera I would like to work on this issue pls. assign it to me

**Comment by Debshibraj123** [comment]
@freecoursera  I want to work please assign me this

**Comment by DhairyaMajmudar** [comment]
Thank you @vedantmistryy for assigning me this issue , I will be blessed if you  hacktoberfest accepted label to this issue

**Comment by freecoursera** [comment]
@DhairyaMajmudar issue fixed?

**Comment by DhairyaMajmudar** [comment]
Yes @vedantmistryy sir almost complete

**Comment by CodeTorso** [comment]
(Hehe)[https://github.com/freecoursera/freecoursera.github.io/pull/56]
