### ISSUE TITLE
Create a redirecting webpage for courses

### ISSUE THREAD

**Issue by freecoursera** [freecoursera/freecoursera.github.io#4]
create a redirecting webpage for different courses (see image below), css file in which you need to write the css or bootstrap code is available in this path `styles/style-courses.css` 
**_compulsory add navbar, footer and discord invite_**
also refer to one of the  courses on coursera and create UI like that,
footer, header and discord invite shown on index.html, will remain same and intact (copy css of index.html)
![image](https://github.com/freecoursera/freecoursera.github.io/assets/145432625/3e6a925a-14cd-4f82-a45c-3e974bef66f7)

**Comment by CodeTorso** [comment]
which browser do you use @freecoursera

**Comment by CodeTorso** [comment]
I want that too

look great

**Comment by freecoursera** [comment]
@CodeTorso brave

**Comment by saku1331** [comment]
I wish to work on this issue. Kindly assign me this.

**Comment by freecoursera** [comment]
@heetvekariya solved it

**Comment by CodeTorso** [comment]
> I wish to work on this issue. Kindly assign me this.

FInd something else to work check the website to get idea
