### ISSUE TITLE
[BUG] Header is not alinged

### ISSUE THREAD

**Issue by Jony-Jas** [freecoursera/freecoursera.github.io#43]
### What would you like to share?

The header is not aligned in all pages of the courses (see the ss below)

![image](https://github.com/freecoursera/freecoursera.github.io/assets/74784363/2c5c5553-9b66-43ac-af0c-6a5fed6dafe4)

### Wanna Work upon[y/n] ??

I want to work on it !!

**Comment by balogun14** [comment]
@Jony-Jas  i will like to work on this issue sir

**Comment by Jony-Jas** [comment]
> @Jony-Jas  i will like to work on this issue sir
> 
> 

I've already requested above 🙂

**Comment by balogun14** [comment]
@Sidhuavneet i noticed the mobile view is not really responsive also the images look wierd

**Comment by Debshibraj123** [comment]
I am interested oplease assign me this

**Comment by freecoursera** [comment]
@Jony-Jas @balogun14 fix

**Comment by balogun14** [comment]
@freecoursera okay I’ll start working on it now

**Comment by CodeTorso** [comment]
> @Sidhuavneet i noticed the mobile view is not really responsive also the images look weird

Create separate issues. This only help you when getting PR merged.

**Comment by CodeTorso** [comment]
> I am interested please assign me this

The issue is already solved before you commented
