### ISSUE TITLE
Styling the footer

### ISSUE THREAD

**Issue by rashen33** [freecoursera/freecoursera.github.io#45]
### What would you like to share?

Hey @freecoursera. I can style the footer and make it responsive. If you want me to work on it please assign me under hactomberfest tag. 

### Wanna Work upon[y/n] ??

yes

**Comment by freecoursera** [comment]
@rashen33 go ahead, but before raising pr, pull first.
thank you

**Comment by CodeTorso** [comment]
We need to work on this in future

**Comment by rashen33** [comment]
Let me know what are the things that I have to do.

**Comment by CodeTorso** [comment]
ok here you go

**Comment by CodeTorso** [comment]
Wait for 1 day. Website is converting to React. Let's deal with this issue after that

**Comment by rashen33** [comment]
Okay!!! @freecoursera

**Comment by CodeTorso** [comment]
I am @CodeTorso. @freecoursera is the owner. I am a maintainer
