### ISSUE TITLE
[BUG] INDEX.html that is front-page path variables changed so page not loading properly

### ISSUE THREAD

**Issue by Sidhuavneet** [freecoursera/freecoursera.github.io#46]
### What would you like to share?

The main page index.html is not opening as expected as shown in below SS .This was because of change in path of different imports such as imported images or css files

![image](https://github.com/freecoursera/freecoursera.github.io/assets/94036516/81e66cb0-285d-4b45-bb0b-aa8a6e5e29ab)
![image](https://github.com/freecoursera/freecoursera.github.io/assets/94036516/8cb167f4-0ec4-44aa-9f68-ad5f669ef942)

### Wanna Work upon[y/n] ??

yes

**Comment by freecoursera** [comment]
@Sidhuavneet 
![image](https://github.com/freecoursera/freecoursera.github.io/assets/145432625/68bd3dc1-1818-4253-bc08-b6de2415dbe5)
when hover a card and screen is scroll down see the above image as result, and fix this.
thank you

**Comment by Chetax** [comment]
can i work on this issue,please assign it to me.

**Comment by CodeTorso** [comment]
You could do it. 

but now position is static for that header menu. 

You could change it to `position: sticky' but not 'position: absolute' ok.

Use z-index if you need check the website before starting.

**Comment by Chetax** [comment]
@CodeTorso  Sir Please Ellaborate What Is Expected To Does Please

**Comment by CodeTorso** [comment]
Stay here for 2 mins

**Comment by CodeTorso** [comment]
So when this issue was created that scrollbar was set to have position absolute
now after one of my PR the position is back to static

**Comment by CodeTorso** [comment]
So the issue of courses cards appearing over navigation tab is solved.

**Comment by CodeTorso** [comment]
You could however use 'position: sticky;' with the navbar and `z-index: 1` to make the nav bar again scroll with scrollbar

**Comment by CodeTorso** [comment]
but that top `.contribution-request` div seems to have some problem. Use LLM tools like ChatGPT to solve that.

**Comment by Chetax** [comment]
@CodeTorso  Got it  Thanks !!!
Going To Solve `contribution-request div seems to have some problem` this issue.

**Comment by CodeTorso** [comment]
Sir is a respectful thing. I have not done anything like that neither I am older than you. So just call hey friend or something.

**Comment by CodeTorso** [comment]
Closing issue since first issue is solved
