### ISSUE TITLE
Play store icon issure

### ISSUE THREAD

**Issue by khushal1512** [freecoursera/freecoursera.github.io#48]
### What would you like to share?

The App Store and Play Store Image doesnt load when we open the website as the image location is not correct in the index.html 

### Wanna Work upon[y/n] ??

y

**Comment by khushal1512** [comment]
Please assign me this issue. Im a beginner i will increase the quality of contirbution

**Comment by CodeTorso** [comment]
Yeah you can work upon this issue. Try getting better icons through Flaticon, Fontawesome or some other platform you may know.

**Comment by CodeTorso** [comment]
Try try but not cry.
