### ISSUE TITLE
[ENHANCEMENT - UI/UX] Add Hover Effects for "Get Started" Button and Social Media Icons

### ISSUE THREAD

**Issue by ayushichoudhary-19** [freecoursera/freecoursera.github.io#49]
### What would you like to share?

**Current Behavior**:
Currently, there are no hover effects applied to the "GetStarted" button or the social media icons, which makes the user experience less engaging.

**Expected Behavior**:
The "GetStarted" button and social media icons should have hover effects that provide visual feedback to users when they interact with them.

**Proposed Solution**:
I would like to work on adding hover effects to the "GetStarted" button and social media icons. To achieve this, I propose the following steps:
1. Identify the CSS rules responsible for styling these elements.
2. Add CSS code to define hover effects, such as changing the background color or adding a subtle animation.
3. Test the changes to ensure they work as expected.

### Wanna Work upon[y/n] ??

Yes!

**Comment by CodeTorso** [comment]
You need to work upon `:hover` and ':active' pseudo classes you know that right?

Also try to make get started button more like 3D when in hover state
for example https://mailchimp.com/es/?currency=USD 
I think you need to two divs with bottom one set to relative and upper one absolute. Try that if you want.

**Comment by ayushichoudhary-19** [comment]
Got it! Thank you for the suggestions.
