### ISSUE TITLE
REACT APP CONVERSION

### ISSUE THREAD

**Issue by Roar022** [freecoursera/freecoursera.github.io#53]
### Description

Converting this HTML, CSS, JS project to REACT JS. Making reusable components. Adjusting script.js, etc.

### Wanna Work upon[y/n] ??

**YES**

**Comment by CodeTorso** [comment]
Get the latest Remote repo or whatever the latest version you have.

We will try to resolve merge conflicts later.

Best of Luck.

**Comment by CodeTorso** [comment]
Tomorrow morning
