### ISSUE TITLE
[FEATURE 💡] Making dynamic course pages

### ISSUE THREAD

**Issue by dipeshhhh** [freecoursera/freecoursera.github.io#57]
### Description

Current pages for courses are static, i.e. a new html file is created for a new course.
Make them dynamic by storing the page data in JSON objects and loading it on a dynamic html page using JS.

This will improve:
- Re-usability (adding new courses less hectic and more quick)
- Easy backend implementation (if in future you decide to implement the backend)

### Wanna Work upon[y/n] ??

yes

**Comment by CodeTorso** [comment]
You can try again after tomorrow's React conversion
