### ISSUE TITLE
[FEATURE 💡] Non-Responsive Sign-In Form on Mobile Devices.

### ISSUE THREAD

**Issue by Haris-Mohanty** [freecoursera/freecoursera.github.io#67]
## Issue Summary:

The sign-in form in the project is not responsive, which causes usability problems on mobile devices with smaller screens. When attempting to access the sign-in page on a smartphone or tablet, the form does not adapt to the screen size, making it challenging to use.

## Reproduction Steps:
Open the project on a mobile device (e.g., smartphone or tablet).
Navigate to the sign-in page.
Attempt to use the sign-in form.

## Expected Behaviour:
The sign-in form should adjust its layout and styling to fit the smaller screen size of the mobile device. Users should be able to easily enter their credentials and sign in.

## Screenshots :
![Screenshot 2023-10-01 095350](https://github.com/freecoursera/freecoursera.github.io/assets/108195360/db2813ee-4355-4d20-9fdd-4c926d46316d)

### Wanna Work upon[y/n] ??

Yes, Please assign me to this issue.

**Comment by Haris-Mohanty** [comment]
Thank You @vedantmistryy , Please add the Hacktoberfest label.

**Comment by Haris-Mohanty** [comment]
@vedantmistryy  Please verify the pull request and please add  Hacktoberfest label.

**Comment by CodeTorso** [comment]
@Haris-Mohanty you are great at explaining issue. Just learn to resolve merge conflicts. Would  be really helpful for you
