### ISSUE TITLE
The site is not responsive

### ISSUE THREAD

**Issue by balogun14** [freecoursera/freecoursera.github.io#90]
### What would you like to share?

I noticed there was no responsiveness i have started working on this by using bootstrap for it 

### Wanna Work upon[y/n] ??

yes

**Comment by CodeTorso** [comment]
Stop working

**Comment by CodeTorso** [comment]
Wait for 15 hours. Website is switching to React.

**Comment by CodeTorso** [comment]
Also I can't assign this to you. There are other's working on this same
